<a href="https://colab.research.google.com/github/nishant26baisoya-code/Data-science_gen_-ai_project/blob/main/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [6]:
#Load the Dataset and create a df
df=pd.read_csv("customer_churn_dataset.csv")
df.head()

,CustomerID,Tenure,MonthlyCharges,TotalCharges,ContractType,TechSupport,Complaints,Churn
0,1,39,74.42,4265.19,One Year,Yes,No,No
1,2,52,56.04,2302.31,Monthly,No,No,Yes
2,3,29,21.06,567.51,Monthly,Yes,Yes,No
3,4,15,95.38,1917.01,Two Year,No,Yes,No
4,5,43,65.06,3377.32,One Year,No,No,No

In [7]:
df.columns

Index(['CustomerID', 'Tenure', 'MonthlyCharges', 'TotalCharges',
       'ContractType', 'TechSupport', 'Complaints', 'Churn'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      58 non-null     int64
 1   Tenure          58 non-null     int64
 2   MonthlyCharges  58 non-null     float64
 3   TotalCharges    58 non-null     float64
 4   ContractType    58 non-null     object
 5   TechSupport     58 non-null     object
 6   Complaints      58 non-null     object
 7   Churn           58 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 3.8+ KB

In [9]:
df.isnull().sum()

CustomerID        0
Tenure            0
MonthlyCharges    0
TotalCharges      0
ContractType      0
TechSupport       0
Complaints        0
Churn             0
dtype: int64

In [10]:
#Here i need to perform some preprocessing

#Here we have 3 categorical columns-->need to be encoded to numerical columns
#1.ContractType
#2.TechSupport
#3.Complaints

#Here we use both encoding techniques--->Label Encoder and one-hot encoder
#1.ContractType----->I will go for--->one-hot Encoder
#2.TechSupport------>I wil go for---->Label Encoder
#3.Complaints------->I will go for--->Label Encoder

In [11]:
#for any sklearn algorithms

#1. initialize
label_encoder=LabelEncoder()

#applying label_encoder on the column-->ContractType

df["Complaints"]=label_encoder.fit_transform(df["Complaints"])
#LAbel encoding is done on the column(Complaints) and i will assign/store it
# in the same column

#applying label_encoder on the column-->TechSupport

df["TechSupport"]=label_encoder.fit_transform(df["TechSupport"])
#LAbel encoding is done on the column(TechSupport) and i will assign/store it
# in the same column

df.head()

,CustomerID,Tenure,MonthlyCharges,TotalCharges,ContractType,TechSupport,Complaints,Churn
0,1,39,74.42,4265.19,One Year,1,0,No
1,2,52,56.04,2302.31,Monthly,0,0,Yes
2,3,29,21.06,567.51,Monthly,1,1,No
3,4,15,95.38,1917.01,Two Year,0,1,No
4,5,43,65.06,3377.32,One Year,0,0,No

In [12]:
#Next is encoding another column(Contractype)-->using one-hot encoder
#before this,check how many unique row values for the column(contract-type)
df['ContractType'].value_counts()

ContractType
One Year    20
Two Year    20
Monthly     18
Name: count, dtype: int64

In [13]:
#we have 3 unique values--->so 3 columns will be generated for one-hot encoder
#another way of one-hot encoding using pandas
df=pd.get_dummies(df,columns=['ContractType'],drop_first=True,dtype=int)
df.head()

,CustomerID,Tenure,MonthlyCharges,TotalCharges,TechSupport,Complaints,Churn,ContractType_One Year,ContractType_Two Year
0,1,39,74.42,4265.19,1,0,No,1,0
1,2,52,56.04,2302.31,0,0,Yes,0,0
2,3,29,21.06,567.51,1,1,No,0,0
3,4,15,95.38,1917.01,0,1,No,0,1
4,5,43,65.06,3377.32,0,0,No,1,0

In [14]:
#The pandas.get_dummies() function is for converting string(categorical values) into
#indicator variables
#Here it encodes with 1/0 or True/False
#This is one-hot encoding process in pandas

In [15]:
#example of one-hot encoding wih pandas
import pandas as pd
#sample dataframe
data={'Products':['Lg','Sony','Samsung','Sony','Lg',None]}
df1=pd.DataFrame(data)
print(df1)
df1['Products'].value_counts()
print("\n")
#1)Apply get_dummies
df_encoded1=pd.get_dummies(df1,columns=['Products'])
print(df_encoded1)
print("\n")

#2)Apply get_dummies with drop_first
df_encoded2=pd.get_dummies(df1,columns=['Products'],drop_first=True)
print(df_encoded2)
print("\n")

#3)Apply get_dummies with dummy_na
df_encoded3=pd.get_dummies(df1,columns=['Products'],dummy_na=True)
print(df_encoded3)
print("\n")

#4)Apply get_dummies with dummy_na and dtype
df_encoded4=pd.get_dummies(df1,columns=['Products'],dummy_na=True,dtype=int)
print(df_encoded4)

  Products
0       Lg
1     Sony
2  Samsung
3     Sony
4       Lg
5     None


   Products_Lg  Products_Samsung  Products_Sony
0         True             False          False
1        False             False           True
2        False              True          False
3        False             False           True
4         True             False          False
5        False             False          False


   Products_Samsung  Products_Sony
0             False          False
1             False           True
2              True          False
3             False           True
4             False          False
5             False          False


   Products_Lg  Products_Samsung  Products_Sony  Products_nan
0         True             False          False         False
1        False             False           True         False
2        False              True          False         False
3        False             False           True         False
4         True             False          False         False
5        False             False          False          True


   Products_Lg  Products_Samsung  Products_Sony  Products_nan
0            1                 0              0             0
1            0                 0              1             0
2            0                 1              0             0
3            0                 0              1             0
4            1                 0              0             0
5            0                 0              0             1

In [16]:
df.head()

,CustomerID,Tenure,MonthlyCharges,TotalCharges,TechSupport,Complaints,Churn,ContractType_One Year,ContractType_Two Year
0,1,39,74.42,4265.19,1,0,No,1,0
1,2,52,56.04,2302.31,0,0,Yes,0,0
2,3,29,21.06,567.51,1,1,No,0,0
3,4,15,95.38,1917.01,0,1,No,0,1
4,5,43,65.06,3377.32,0,0,No,1,0

In [17]:
#Split the dataset into input variables and ouput variable
X=df.drop(columns=['CustomerID','Churn']) #input variables
y=df['Churn'].apply(lambda x:1 if x=='Yes' else 0)   #output column converting yes/No to 1/0

#we are removing the sequence column(customerid) and output column(churn) from input df
X.head()

,Tenure,MonthlyCharges,TotalCharges,TechSupport,Complaints,ContractType_One Year,ContractType_Two Year
0,39,74.42,4265.19,1,0,1,0
1,52,56.04,2302.31,0,0,0,0
2,29,21.06,567.51,1,1,0,0
3,15,95.38,1917.01,0,1,0,1
4,43,65.06,3377.32,0,0,1,0

In [18]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Churn, dtype: int64

In [19]:
#Splitting the data into trainset and test set and i will perform scaling
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=3)

In [20]:
#Each input column having diff values, i need to scale

In [21]:
#Scaling---->StandardScaler
from sklearn.preprocessing import StandardScaler
#i.initialize
scaler=StandardScaler()

#ii.fit and Transform
#Scaling both X_train and X_test (reconstructing X_train and X_test by scaling)
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
#we see the values b/w -3 to +3

In [22]:
X_train

array([[ 0.6573479 ,  0.20206494,  0.76793909, -0.83887049, -0.91651514,
         1.51185789, -0.73029674],
       [ 1.00624794,  0.35221242, -1.32091408,  1.19207912,  1.09108945,
         1.51185789, -0.73029674],
       [-0.73825226,  0.61389803, -0.29221216,  1.19207912,  1.09108945,
        -0.66143783, -0.73029674],
       [ 1.12254795,  1.40925069,  0.26829122, -0.83887049,  1.09108945,
        -0.66143783, -0.73029674],
       [ 0.59919789, -1.16384816, -0.16768613,  1.19207912, -0.91651514,
        -0.66143783,  1.36930639],
       [-0.56380224, -1.62329945, -0.96412004, -0.83887049, -0.91651514,
        -0.66143783, -0.73029674],
       [ 1.18069796,  0.98068688, -1.71014876, -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [-0.56380224,  0.12141429,  1.55263626,  1.19207912, -0.91651514,
         1.51185789, -0.73029674],
       [ 0.48289788, -0.27197211,  0.92301396, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [ 0.25029785,  0.86142688, -1.5621568 ,  1.19207912, -0.91651514,
         1.51185789, -0.73029674],
       [ 0.07584783,  1.56754904,  1.78395836,  1.19207912, -0.91651514,
        -0.66143783, -0.73029674],
       [-1.20345231,  1.1286894 ,  1.43563959,  1.19207912, -0.91651514,
        -0.66143783, -0.73029674],
       [ 1.35514798,  0.71042141,  0.6895125 , -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [ 0.42474787, -0.93862693, -0.69342574, -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [ 1.35514798,  0.71042141,  0.6895125 , -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [-1.66865236,  1.44786005, -0.58196827, -0.83887049,  1.09108945,
        -0.66143783,  1.36930639],
       [-0.38935222,  1.5817058 , -0.61588452,  1.19207912,  1.09108945,
        -0.66143783, -0.73029674],
       [-0.97085228, -0.37578837, -1.25938508, -0.83887049, -0.91651514,
        -0.66143783, -0.73029674],
       [-1.72680237,  0.22694652,  0.28961562, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [-1.37790233, -0.40839183,  0.75711797,  1.19207912,  1.09108945,
        -0.66143783,  1.36930639],
       [ 0.59919789, -1.16384816, -0.16768613,  1.19207912, -0.91651514,
        -0.66143783,  1.36930639],
       [ 1.18069796, -0.18488657, -0.04554376, -0.83887049, -0.91651514,
        -0.66143783, -0.73029674],
       [-0.2730522 , -0.78376053, -0.01927797, -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [-0.15675219, -1.68550341, -1.35830367,  1.19207912,  1.09108945,
        -0.66143783, -0.73029674],
       [-0.44750222, -0.37493039,  0.37650992, -0.83887049,  1.09108945,
        -0.66143783, -0.73029674],
       [ 0.30844786,  0.50364688, -1.10154818,  1.19207912, -0.91651514,
        -0.66143783,  1.36930639],
       [-0.44750222, -1.01713262, -1.30089881, -0.83887049, -0.91651514,
        -0.66143783, -0.73029674],
       [-1.72680237,  0.22694652,  0.28961562, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [ 1.23884797, -1.10550513, -0.76259762,  1.19207912, -0.91651514,
        -0.66143783,  1.36930639],
       [-0.91270228, -0.27797801, -0.50942898, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [-1.1453023 ,  1.16729875,  0.50847453, -0.83887049,  1.09108945,
        -0.66143783, -0.73029674],
       [ 1.23884797,  1.15957688,  1.60935251,  1.19207912, -0.91651514,
        -0.66143783, -0.73029674],
       [ 0.71549791,  0.28271559,  0.60298143, -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [-0.2149022 , -1.67735255,  1.56306387,  1.19207912, -0.91651514,
        -0.66143783,  1.36930639],
       [-1.66865236,  1.44786005, -0.58196827, -0.83887049,  1.09108945,
        -0.66143783,  1.36930639],
       [ 1.58774801, -0.7142637 , -0.90211431, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [ 0.88994793, -0.72370154, -0.39094914, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [ 0.71549791, -1.04844909, -0.70302853,  1.19207912, -0.91651514,
        -0.66143783, -0.73029674],
       [-0.50565223,  0.36250825,  1.8909663 , -0.83887049,  1.09108945,
         1.51185789, -0.73029674],
       [-0.56380224, -1.62329945, -0.96412004, -0.83887049, -0.91651514,
        -0.66143783, -0.73029674],
       [-1.72680237, -0.18746053,  0.05055983,  1.19207912,  1.09108945,
        -0.66143783,  1.36930639],
       [ 0.42474787,  0.6036022 ,  1.43980913,  1.19207912, -0.91651514,
         1.51185789, -0.73029674],
       [ 1.529598  , -0.90387852,  0.36897297, -0.83887049,  1.09108945,
        -0.66143783, -0.73029674],
       [-0.97085228,  1.50277112, -0.33710843, -0.83887049,  1.09108945,
        -0.66143783,  1.36930639],
       [-0.09860219,  0.7649035 , -1.19544971,  1.19207912, -0.91651514,
         1.51185789, -0.73029674],
       [ 1.12254795, -1.68250046,  1.65038193, -0.83887049,  1.09108945,
         1.51185789, -0.73029674]])

In [23]:
X_test

array([[ 1.47144799,  0.34878048, -0.40477444,  1.19207912, -0.91651514,
         1.51185789, -0.73029674],
       [-0.44750222, -0.38908715, -0.83705899,  1.19207912,  1.09108945,
         1.51185789, -0.73029674],
       [ 1.58774801, -0.7142637 , -0.90211431, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [-1.20345231, -1.13596362,  0.96404338, -0.83887049, -0.91651514,
         1.51185789, -0.73029674],
       [-0.62195224, -1.67606557,  0.4804153 ,  1.19207912,  1.09108945,
        -0.66143783,  1.36930639],
       [ 1.58774801, -0.7142637 , -0.90211431, -0.83887049, -0.91651514,
        -0.66143783,  1.36930639],
       [-1.66865236,  0.21750868, -0.08304686,  1.19207912,  1.09108945,
        -0.66143783, -0.73029674],
       [ 0.71549791,  1.44914702,  0.86685011, -0.83887049, -0.91651514,
         1.51185789, -0.73029674],
       [ 0.36659787, -0.61044744,  0.52906491, -0.83887049, -0.91651514,
         1.51185789, -0.73029674],
       [-0.62195224,  0.05663638, -0.95914082,  1.19207912, -0.91651514,
        -0.66143783, -0.73029674],
       [ 1.529598  ,  0.83397134,  0.86414105,  1.19207912, -0.91651514,
        -0.66143783,  1.36930639],
       [ 0.71549791,  1.44914702,  0.86685011, -0.83887049, -0.91651514,
         1.51185789, -0.73029674]])

In [24]:
X_train[0] #for 1st record

array([ 0.6573479 ,  0.20206494,  0.76793909, -0.83887049, -0.91651514,
        1.51185789, -0.73029674])

In [25]:
X_train.shape   #80% data

(46, 7)

In [26]:
X_train[0]

array([ 0.6573479 ,  0.20206494,  0.76793909, -0.83887049, -0.91651514,
        1.51185789, -0.73029674])

In [27]:
X_test.shape   #20% data

(12, 7)

In [28]:
#Next is--->
#1.Model initializing,
#2.Model Training,
#3.Model Predicting ,
#4.Model Evaluation

In [29]:
from sklearn.linear_model import LogisticRegression
#1.Model initialization
logistic_reg_model=LogisticRegression()

#2.Model training--->using X_train and y_train
logistic_reg_model.fit(X_train,y_train)

LogisticRegression()

In [30]:
#Now model got trained
#iii.Model Prediction---->on X_test(unseen data-20%)
y_pred=logistic_reg_model.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [31]:
X_test.shape

(12, 7)

In [93]:
print(y_test.values)    #Actual data
print(y_pred)    #Predicted data

[0 0 1 0 0 1 0 1 0 0 0 1]
[0 0 1 0 0 1 0 0 0 0 0 0]

In [94]:
#out of 12---->10predictions are correct
#         ---->2predictions are wrong

In [32]:
#X_test has 12 records--->For this 12 reords, it has predicted
#whether it is churn/Not Churn

In [33]:
y_test

46    0
13    0
55    1
12    0
6     0
36    1
18    0
23    1
25    0
27    0
30    0
51    1
Name: Churn, dtype: int64

In [34]:
#How many correct/in-correct predictions
#i.e comparing predicted and actual values
#Next is Evaluation metrics for classification

#Previously-->for Regression we had -R_score,MAE,MSE.RMSE
#All the above are evaluation metrics if the target variables are continous

In [35]:
#Evaluation metrics for Classification---->we have Confusion Matrix
"""
In Confusion MAtrix--->we keep Actual and predicted in tabular form

                 Predicted
                 1              0
          1 | True +ve | False -ve
Actual      |
          0 | False +ve| True -ve

    1) Actual value is 1 and predicted value is 1--->we call it as-------->True Positive
     Here Employee is churn(1) and model predicted also as churn(1)------->True Positive

   2) Actual value is 0 and predicted value is 0--->we call it as---     --->True Negative
     Here Employee is not churn(0) and model predicted also as not churn(0)->True Negative

   3) Actual value is 0 and predicted value is 1--->we call it as------>False Positive
     Here Employee is not churn(0) but model predicted as churn(1)----->False Positive

   4) Actual value is 1 and predicted value is 0--->we call it as------>False Negative
      Here Employee is churn(1) but model predicted as not churn(0)----->False Negative


   In our predicted results-->If you have more True+ve's and True-ve's-->then it is Good
   If you have more False+ve's and False-ve's-->then it is Bad(ur model should not predict these)

   Your model should reduce False+ve's and False-ve's
"""

"\nIn Confusion MAtrix--->we keep Actual and predicted in tabular form\n\n                 Predicted\n                 1              0\n          1 | True +ve | False -ve\nActual      |\n          0 | False +ve| True -ve\n\n    1) Actual value is 1 and predicted value is 1--->we call it as-------->True Positive\n     Here Employee is churn(1) and model predicted also as churn(1)------->True Positive\n\n   2) Actual value is 0 and predicted value is 0--->we call it as---     --->True Negative\n     Here Employee is not churn(0) and model predicted also as not churn(0)->True Negative\n\n   3) Actual value is 0 and predicted value is 1--->we call it as------>False Positive\n     Here Employee is not churn(0) but model predicted as churn(1)----->False Positive\n\n   4) Actual value is 1 and predicted value is 0--->we call it as------>False Negative\n      Here Employee is churn(1) but model predicted as not churn(0)----->False Negative\n\n\n   In our predicted results-->If you have more True+ve's and True-ve's-->then it is Good\n   If you have more False+ve's and False-ve's-->then it is Bad(ur model should not predict these)\n\n   Your model should reduce False+ve's and False-ve's\n"

In [36]:
#How Accuracy is calculated
"""
1)Accuracy=(TP+TN)/(TP+TN+FP+FN)

i.e Accuracy = ratio of correct predictions/total predictions

=========================================================================================
I want to focus to reduce False -ve's
ex: healthcare usecases
    patient has----> Covid
    but model predicted as ----->Non-Covid
    but covid case is a critical case

ex:2
    Banking customer----->is a defaulter(not paying the loans)
    but model predicted as non-defaulter
    It is a critical case

    For these kind of critical usecases like banking ,healthcare
    people concentrate more on to reduce False -ve's
    They want to avoid false -ve

    so apart from accuracy ,a new metric called  as--->Recall is used
    Recall also called as Sensitivity

    Recall=TP/(TP+FN)

    Recall ---->concentraing on False -ve's
=========================================================================================
Some usecases ----->more towards False +ve's

for that we have another metric called as ---->Precision

precision=TP/(TP+FP)

precision ---->concentraing on False +ve's
==========================================================================================
Some usecases focuses on reducing False -ves
some usecases focuses on reducing False +ves
Too many False+ve's and too many False-ve's are not good

so overall we want a balanced precision,

for that we have another metrics called as F1_score

F1_score=2*Precision*Recall/(Precision+Recall)

i.e F1_score is harmonic mean of Precision and Recall

whever people want balanced precision and recall ,they prefer F1_score

To test your model accuracy---->we go for F1_score

Based on Confusion matrix,

you can calculate your----------->accuracy
you can calculate your----------->precision(for False+ve's)
you can calculate your----------->recall(for False-ve's)
you can calculate your----------->F1_score(for both False+ve's and False-ve's balance)
                                            ie Precision+recall mean

all these we wont calculate manually

These metrics are specific to classification problems

Various possibilities of confusion matrix

   Actual      Predicted
     1            0   ----------->False -ve
     0            1   ----------->False +ve
     1            1   ----------->True +ve
     0            0   ----------->True -ve

These are given by probabilities

If you have too many TP & TN--->then ur accuracy will be high

If you have too many FP & FN--->then ur accuracy will be low

To overcome this,we have another metrics called as--->ROC-AUC score
==========================================================================================
ROC-AUC Score:

ROC--->Receiver Operating Characteristics
AUC--->Area Under Curve

As part of Accuracy,
they came up with 2 things
1)TPR(True Positive Rate) ----->as y-axis
2)FPR(False Positive Rate)----->as x-axis
TPR
|
|   /------------- whenever it is making a curve like this
|  /               we want to make sure, the area under curve(AUC) is more
| /            --->here the area is more and should be more,
|/_______________  that means your model is doing good
      FPR
TPR
|
|   /-------------
|__/_______________---->here the Area under the curve(AUC) is less
      FPR               that means your model is doing bad

whenever it is making a curve,make sure the area under curve is more--->model is doing good


TPR----->is nothing but Recall (False -ve)
         Recall=TP/(TP+FN)

FPR----->is nothing but False Positive Rate
         FPR=FP/(FP+TN)

AUC ---->is the ratio of TPR/FPR

AUC should be high----->then ur model is doing good
AUC should be low----->then ur model is doing bad

These all are the different metrics
which are related to classification

While implementing these--->we check for--->
            1.what is the accuracy
            1.what is Recall score
            2.what is precision score
            3.what is F1 Score
            4.what is ROC - AUC score
"""

"\n1)Accuracy=(TP+TN)/(TP+TN+FP+FN)\n\ni.e Accuracy = ratio of correct predictions/total predictions\n\n=========================================================================================\nI want to focus to reduce False -ve's\nex: healthcare usecases\n    patient has----> Covid\n    but model predicted as ----->Non-Covid\n    but covid case is a critical case\n\nex:2\n    Banking customer----->is a defaulter(not paying the loans)\n    but model predicted as non-defaulter\n    It is a critical case\n\n    For these kind of critical usecases like banking ,healthcare\n    people concentrate more on to reduce False -ve's\n    They want to avoid false -ve\n\n    so apart from accuracy ,a new metric called  as--->Recall is used\n    Recall also called as Sensitivity\n\n    Recall=TP/(TP+FN)\n\n    Recall ---->concentraing on False -ve's\n=========================================================================================\nSome usecases ----->more towards False +ve's\n\nfor that we have another metric called as ---->Precision\n\nprecision=TP/(TP+FP)\n\nprecision ---->concentraing on False +ve's\n==========================================================================================\nSome usecases focuses on reducing False -ves\nsome usecases focuses on reducing False +ves\nToo many False+ve's and too many False-ve's are not good\n\nso overall we want a balanced precision,\n\nfor that we have another metrics called as F1_score\n\nF1_score=2*Precision*Recall/(Precision+Recall)\n\ni.e F1_score is harmonic mean of Precision and Recall\n\nwhever people want balanced precision and recall ,they prefer F1_score\n\nTo test your model accuracy---->we go for F1_score\n\nBased on Confusion matrix,\n\nyou can calculate your----------->accuracy\nyou can calculate your----------->precision(for False+ve's)\nyou can calculate your----------->recall(for False-ve's)\nyou can calculate your----------->F1_score(for both False+ve's and False-ve's balance)\n                                            ie Precision+recall mean\n\nall these we wont calculate manually\n\nThese metrics are specific to classification problems\n\nVarious possibilities of confusion matrix\n\n   Actual      Predicted\n     1            0   ----------->False -ve\n     0            1   ----------->False +ve\n     1            1   ----------->True +ve\n     0            0   ----------->True -ve\n\nThese are given by probabilities\n\nIf you have too many TP & TN--->then ur accuracy will be high\n\nIf you have too many FP & FN--->then ur accuracy will be low\n\nTo overcome this,we have another metrics called as--->ROC-AUC score\n==========================================================================================\nROC-AUC Score:\n\nROC--->Receiver Operating Characteristics\nAUC--->Area Under Curve\n\nAs part of Accuracy,\nthey came up with 2 things\n1)TPR(True Positive Rate) ----->as y-axis\n2)FPR(False Positive Rate)----->as x-axis\nTPR\n|\n|   /------------- whenever it is making a curve like this\n|  /               we want to make sure, the area under curve(AUC) is more\n| /            --->here the area is more and should be more,\n|/_______________  that means your model is doing good\n      FPR\nTPR\n|\n|   /-------------\n|__/_______________---->here the Area under the curve(AUC) is less\n      FPR               that means your model is doing bad\n\nwhenever it is making a curve,make sure the area under curve is more--->model is doing good\n\n\nTPR----->is nothing but Recall (False -ve)\n         Recall=TP/(TP+FN)\n\nFPR----->is nothing but False Positive Rate\n         FPR=FP/(FP+TN)\n\nAUC ---->is the ratio of TPR/FPR\n\nAUC should be high----->then ur model is doing good\nAUC should be low----->then ur model is doing bad\n\nThese all are the different metrics\nwhich are related to classification\n\nWhile implementing these--->we check for--->\n            1.what is the accuracy\n            1.what is Recall score\n            2.what is precision score\n            3.what is F1 Score\n            4.what is ROC - AUC score\n"

In [37]:
#Evaluation metrics for classification(Logistic Regression)
from sklearn.metrics import classification_report,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
#For confusion matrix --->we are importing classification_report

#for all these evaluations, I want y_test(actual) and y_pred(pred) value

In [38]:
y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [39]:
X_test.shape

(12, 7)

In [40]:
print("Classification Report for Logistic Regression Model:")
print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))
print("Precision Score:",precision_score(y_test,y_pred))
print("Recall Score:",recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))
print("ROC-AUC Score:",roc_auc_score(y_test,logistic_reg_model.predict_proba(X_test)[:,1]))
#Here is ROC-AUC score-->instead of y-pred on 0/1 -->We take the probability value
#probability value for 1 --->we consider
#How to get the probability value--->instead of model.predict()
#                                   we say--->model.predict_proba()
#check the below stmt

Classification Report for Logistic Regression Model:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.50      0.67         4

    accuracy                           0.83        12
   macro avg       0.90      0.75      0.78        12
weighted avg       0.87      0.83      0.81        12

Accuracy Score: 0.8333333333333334
Precision Score: 1.0
Recall Score: 0.5
F1 Score: 0.6666666666666666
ROC-AUC Score: 0.75

In [41]:
y_pred=logistic_reg_model.predict(X_test)

In [42]:
#But Roc-AUC--->take the probability value(probability value for 1)
logistic_reg_model.predict_proba(X_test)
#In the o/p we get the probabilty for 0 and probability for 1
#ex: probabilty for 0 is p
#    probability for 1 is 1-p
#ex: probabiliy for 0 is--->0.29
#    probability for 1 is-->1-0.29=0.71

array([[0.70846371, 0.29153629],
       [0.79047195, 0.20952805],
       [0.2849502 , 0.7150498 ],
       [0.87140798, 0.12859202],
       [0.71096794, 0.28903206],
       [0.2849502 , 0.7150498 ],
       [0.80576371, 0.19423629],
       [0.79015038, 0.20984962],
       [0.79520844, 0.20479156],
       [0.61885927, 0.38114073],
       [0.56439689, 0.43560311],
       [0.79015038, 0.20984962]])

In [43]:
#Consider the probability of 1 only from the above, for that
logistic_reg_model.predict_proba(X_test)[:,1]
#Now substitute this in the above ROC-AUC

array([0.29153629, 0.20952805, 0.7150498 , 0.12859202, 0.28903206,
       0.7150498 , 0.19423629, 0.20984962, 0.20479156, 0.38114073,
       0.43560311, 0.20984962])

In [44]:
#here 83% accuracy ,but still consider the F1score and AUCscore
"""
precision score--->1.0----->100% (but it considers only False +ves)
Recall score------>0.5----->50%(checks only for False -ves)
                            (here 50% means there are lot of records failed
                             means--->there are lot of False -ve's
                             i.e actually it is 1--->but predicted as 0
                             i.e false negative cases are more--->bcoz of that
                             F1score--->got reduced
                             (i.e harmonic mean of precision and Recall)

ROC-AUC Score -------->is the  ratio of TPR/FPR --->75%

Always we prefer to check the F1score and ROC-AUC score
rather than Accuracy score bcoz Accuracy score is overlooked
bcoz Accuracy doesnt give much importance to specific Recall and precision
but we have to make sure that the model should reduce the False+Ve's and False-Ve's

So w.r.to F1Score----->it is 66%---->IT is not great

so we are going to explore with rest of the algorithms
"""

"\nprecision score--->1.0----->100% (but it considers only False +ves)\nRecall score------>0.5----->50%(checks only for False -ves)\n                            (here 50% means there are lot of records failed\n                             means--->there are lot of False -ve's\n                             i.e actually it is 1--->but predicted as 0\n                             i.e false negative cases are more--->bcoz of that\n                             F1score--->got reduced\n                             (i.e harmonic mean of precision and Recall)\n\nROC-AUC Score -------->is the  ratio of TPR/FPR --->75%\n\nAlways we prefer to check the F1score and ROC-AUC score\nrather than Accuracy score bcoz Accuracy score is overlooked\nbcoz Accuracy doesnt give much importance to specific Recall and precision\nbut we have to make sure that the model should reduce the False+Ve's and False-Ve's\n\nSo w.r.to F1Score----->it is 66%---->IT is not great\n\nso we are going to explore with rest of the algorithms\n"

In [45]:
print("Classification Report for Logistic Regression Model:")
print("y_actual:",y_test.values)
print("y_pred  :",y_pred)

print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))

print("Precision Score(1):",precision_score(y_test,y_pred))
print("Precision Score(0):",precision_score(y_test,y_pred,pos_label=0))

print("Recall Score(1):",recall_score(y_test,y_pred))
print("Recall Score(0):",recall_score(y_test,y_pred,pos_label=0))

print("F1 Score(1):",f1_score(y_test,y_pred))
print("F1 Score(0):",f1_score(y_test,y_pred,pos_label=0))

print("ROC-AUC Score:",roc_auc_score(y_test,logistic_reg_model.predict_proba(X_test)[:,1]))

Classification Report for Logistic Regression Model:
y_actual: [0 0 1 0 0 1 0 1 0 0 0 1]
y_pred  : [0 0 1 0 0 1 0 0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.50      0.67         4

    accuracy                           0.83        12
   macro avg       0.90      0.75      0.78        12
weighted avg       0.87      0.83      0.81        12

Accuracy Score: 0.8333333333333334
Precision Score(1): 1.0
Precision Score(0): 0.8
Recall Score(1): 0.5
Recall Score(0): 1.0
F1 Score(1): 0.6666666666666666
F1 Score(0): 0.8888888888888888
ROC-AUC Score: 0.75

In [46]:
"""
Total samples=12
Actual positives=4
Actual negatives=8

predicted positves=2
predicted negatives=10

TP=2
TN=8
FP=0
FN=2

Confusion matrix
              Predicted 0             predicted 1
Actual 0        8(TN)                  0(FP)

Actual 1        2(FN)                  2(TP)

No of correctly predicted values=10/12
Here the probelm is ---->imbalanced dataset

why accuracy=0.8(80%)
Accuracy=(TP+TN)/(TP+TN+FP+FN)
        =(2+8)/(2+8+0+2)
        =10/12
        =0.8
Looks good---->But it is misleading
bcoz--->the model is mostly predicting the majority class(0)

for class 1(positive class)
precision(1)=TP/(TP+FP)=2/(2+0) =1
recall(1)=TP/(TP+FN)=2/(2+2)=2/4=1/2=0.5
f1_score(1)=2*precision*recall/(precision+recall)=2*1*0.5/(1.5) =1/1.5 =0.67
The model doing bad in detecting the positive class
class 1---->precision=1  recall=0.5 f1_score=0.67

for class 0(negative class)
precision(0)=TN/(TN+FN)=8/(8+2)=8/10=0.8
recall(0)=TN/(TN+FP)=8/(8+0) =1
f1_score(0)=2*precision*recall/(precision+recall)=2*0.8*1/(0.8+1)=0.89

The model is very good in prediction the negative class(0)

Why F1-score -->should be considered over Accuracy
why F1-score---->should be considered when accuracy already considers TP+TN

bcoz--->1)Acuracy treats all errors equally
        2)F1-score ignores TN completely
        F1-score is harmonic mean of precision and recall
        F1_score=2*Precision*Recall/(Precision+Recall)
        It balances precision and Recall
        it balances-->1)Precision-->How many predicted positves(TP) were corect
                   -->2)Recall --->How many actual positives were predicted correctly
        in imbalanced datsets
        we observe---->high accuracy by predicting only the majority class
        But F1-score will expose that failure

        your mode1---->accuracy=80%
                       but F1_score exposes --->f1 for class 1=0.67
        Looks good---->But it is misleading
        bcoz--->the model is mostly predicting the majority class(0)
        but for class 1(positive class)--->the model is doing bad in detecting the positive class

        Final conclusion:
        The model is good at predicting 0
        completely failed in predicting 1
        Accuracy hides this
        F1-score exposes it


"""

'\nTotal samples=12\nActual positives=4\nActual negatives=8\n\npredicted positves=2\npredicted negatives=10\n\nTP=2\nTN=8\nFP=0\nFN=2\n\nConfusion matrix\n              Predicted 0             predicted 1\nActual 0        8(TN)                  0(FP)\n\nActual 1        2(FN)                  2(TP)\n\nNo of correctly predicted values=10/12\nHere the probelm is ---->imbalanced dataset\n\nwhy accuracy=0.8(80%)\nAccuracy=(TP+TN)/(TP+TN+FP+FN)\n        =(2+8)/(2+8+0+2)\n        =10/12\n        =0.8\nLooks good---->But it is misleading\nbcoz--->the model is mostly predicting the majority class(0)\n\nfor class 1(positive class)\nprecision(1)=TP/(TP+FP)=2/(2+0) =1\nrecall(1)=TP/(TP+FN)=2/(2+2)=2/4=1/2=0.5\nf1_score(1)=2*precision*recall/(precision+recall)=2*1*0.5/(1.5) =1/1.5 =0.67\nThe model doing bad in detecting the positive class\nclass 1---->precision=1  recall=0.5 f1_score=0.67\n\nfor class 0(negative class)\nprecision(0)=TN/(TN+FN)=8/(8+2)=8/10=0.8\nrecall(0)=TN/(TN+FP)=8/(8+0) =1\nf1_score(0)=2*precision*recall/(precision+recall)=2*0.8*1/(0.8+1)=0.89\n\nThe model is very good in prediction the negative class(0)\n\nWhy F1-score -->should be considered over Accuracy\nwhy F1-score---->should be considered when accuracy already considers TP+TN\n\nbcoz--->1)Acuracy treats all errors equally\n        2)F1-score ignores TN completely\n        F1-score is harmonic mean of precision and recall\n        F1_score=2*Precision*Recall/(Precision+Recall)\n        It balances precision and Recall\n        it balances-->1)Precision-->How many predicted positves(TP) were corect\n                   -->2)Recall --->How many actual positives were predicted correctly\n        in imbalanced datsets\n        we observe---->high accuracy by predicting only the majority class\n        But F1-score will expose that failure\n\n        your mode1---->accuracy=80%\n                       but F1_score exposes --->f1 for class 1=0.67\n        Looks good---->But it is misleading\n        bcoz--->the model is mostly predicting the majority class(0)\n        but for class 1(positive class)--->the model is doing bad in detecting the positive class\n\n        Final conclusion:\n        The model is good at predicting 0\n        completely failed in predicting 1\n        Accuracy hides this\n        F1-score exposes it\n\n\n'

In [47]:
# #Decision Tree
# #Constructing a Tree like structure
# #It uses divide and conquer method
# #A Decision Tree is a Tree-structure,where each internal node represents a test
# #Each branch represents outcome of a test
# #Each Leafnode represnts class or Category
# #examples--->refer the diagrams

# #ex: A Customer approached for a loan
# """
#   i/p variable     o/pvariable
#   sal   age        Defaulter/Non-Defaulter (if non-defaulter--->u can approve the loan)
#    -     -          Yes
#    -     -          No
#    -     -          No

#    It builds a decision Tree

# It takes any one i/p variable(sal/age) -->where impurities are less

# here interanlly mthematical calculations

# here we have a method called------>Gini Impurity
# It is given as ======> Gini Impurity =1-sum(pi**2)
#                        here pi is ----->Probability

# Your Dataset should be pure
# For which i/p variable The Gini Impurity is less then that i/p variable
# will be taken as root node
# """
# """
# ex:        sal>40000
#              /  \ -->Here everytime,if sal>40000->directly we can label him as non-defaulter
#         yes /    \No Here there is no other conflict with defaulter
#            /      \  This kind of cases,we call it as homogeneous(only one class/category)
#   Defaulters=0    Defaulters=9
#   No-defaulters=18 Non-Defaulters=9 --->This is not homogeneous(bcoz of multiple categories)
#     |                 |                  IT is heterogeneous(2 classes/categories)
# (Homogeneous)         |                  (i.e 9 defaulters and 9 non-defaulters)
#                       |                  For heterogeneous we need to go for further splitting
#                     Age >30
#                      / \
#                 yes /   \No
#                    /     \
#     homogeneous  D=9     D=0   (homogeneous-->stop leaf node splitting or processing)
# stop splitting  ND=0     ND=9

# Whenever your leaf node reaches homogeneous then you can stop splitting the leaf node further

# This is how Decision Tree internally building tree structure for your dataset
# through which it is going to learn
# -here we used 2 columns(sal and age) but in real-usecases,it uses any no of columns

# -It uses a mechanism that which column can be put as root node and which column as
#  internal node and leaf node is calculated

# -Here one of the method to perform this is--->Gini Impurity =(1-sum(pi)square)

# -another method is---->Entropy = sum(-pi*log(pi))
#                                  i.e sum of negative probability score * log(pi)

# -Here we can go with either Gini Impurity or Entropy

#  we will be passing these (Gini Impurity /Entropy) as hyper parameters while
#  initializing the model

#  Here the Goal/Objective is --->which column can be put as root node or
#  which column if i select as rootnode so that u can traverse/reach the leaf node quickly

#  ex:  if i select salary, then i am able to reach the leaf node quickly

#  in which feature ur Gini Impurity/Entropy is less i.e pure and more pure
# i.e which is more homogeneous

#  if it is impure means, it is completely heterogenous

#  what we are achieving here --->whether we are able to traverse(reach) to leafnode quickly

#  -This is how Decision Tree Algorithm uses uses Gini impurity/Entropy in
#   computing/selecting rootnodes/internal nodes and leaf nodes through which it is
#   going to learn and predict

#   -Internally it builds complex nested if-else logic

**Decision Tree Algorithm implementation**

In [48]:
from sklearn.tree import DecisionTreeClassifier
#4 Things we perform

#1. Initialize the model
dt_model=DecisionTreeClassifier()

#2.applying fit--->Train the model with(X_train,y_train)
dt_model.fit(X_train,y_train)

#Now model got trained
#3.Model prediction on test data(X_test)--->we get y_pred
dt_model.predict(X_test)

#4.Model evaluation
y_pred=dt_model.predict(X_test)

print("Classification Report for Decision Tree Model:")
print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))
print("Precision Score:",precision_score(y_test,y_pred))
print("Recall Score:",recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))
print("ROC-AUC Score:",roc_auc_score(y_test,dt_model.predict_proba(X_test)[:,1]))

Classification Report for Decision Tree Model:
              precision    recall  f1-score   support

           0       0.71      0.62      0.67         8
           1       0.40      0.50      0.44         4

    accuracy                           0.58        12
   macro avg       0.56      0.56      0.56        12
weighted avg       0.61      0.58      0.59        12

Accuracy Score: 0.5833333333333334
Precision Score: 0.4
Recall Score: 0.5
F1 Score: 0.4444444444444444
ROC-AUC Score: 0.5625

Here if we compare with logistic regression,

Accuracy score,F1Score and ROC-AUC score all are less as compared with logistic regression

so Decision Tree is not doing well

In [49]:
#homogeneous---->all records belongs to the same class
#heterogeneous--->some records of one class
#                 some records of other class

#In heterogeneous,we cannot take better decision
#but in homogeneous,we can take better decision

In [50]:
#In the above example--->by default it is Gini Impurity
#while initializing the model,we provide these hyper parameter as

dt_model=DecisionTreeClassifier(criterion="gini")

#Now change to----->"entropy"  and check the accuracy
dt_model=DecisionTreeClassifier(criterion="entropy")

#It is also doing bad

#This is hyperparamter(learning parameter) exploration-->check with is best

In Linear Regression---->y=mx+c

here y can be -ve or +ve

but in logistic regression-->It should be  +ve only

In Linear Regression---->straight line/Prediction line

In Logistic regression-->S-Curve

IT selects the best S-Curve-->best sigmoid curve

Logistic Regression--->For binary classification-->for 2 classes, it works fine

**Random-Forest Classifier**

In [51]:

# Random Forest ---->we call as Ensemble(Collections)

# collection of Decision Trees---->For classification

# also known as------>Bagging Algorithm

# #Here how the process is happening

# -You want to take a decision

# -Instead of taking decision from a single resource

# -It takes decisions from multiple resources

# -here the final decision is the best decision bcoz

#  u got advices from multiple resources through which you are learning and
#  consolidating which decision is the best one

#  -Normally, taking decisions from multiple resources will increase the confidence and
#   also will be more accurate

# #what Random Forest does is

# we build a Decision-Tree--->based on its traversing--->we get the leaf node
# ex:
# assume u have 100 records

# 1st random-Forest splits ur dataset into multiple sub-sets(samples)-->randomly it splits

# As a Datascientist,I will say--->I want Random Forest with 5 decision Trees
# or
# I want Random Forest with 5 Estimators(5 Decision Trees)

# whether to go with 5 Estimators(or) 50 Estimators--->we need to decide(explore)
# check the results for both and decide
# #ex:
# I want to build Random-Forest with 5 Estimators(5 Decision Trees)
# so it splits 100 recs into 5 Random-splits or 5Bags

# Bag is a collection of records


#     |----------100Records-----------------|
#     |       |        |      |             |---->Random Split
#    Bag1    Bag2    Bag3    Bag4        Bag5
#    (20)    (20)    (20)    (20)        (20)
#     |       |        |      |            |
#    DT1     DT2      DT3    DT4          DT5

#    It created multiple bags and for each bag---->a Decision Tree

#    and all are processed parallely
#    ex:
#    Forest----->collection of Trees
#    ex: u are passing 1 record to predict -->and check whether this candidate win/loose the
#    election

#    when you apply Random Forest classifier, It takes suggestions from all the Decision trees

#    Now for a given candiadate---->

#    DT1     DT2    DT3    DT4    DT5
#     |       |      |      |      |
#    Win     win    Loose  Win   Loose

#    Now Random Forest takes all the o/p's and check with the majority of votes

#    Majotity of votes---->win[3]
#                         Loose[2]
#   so the majority of votes---->is 3---->win

#   So finally the Random Forest predicts as---->win

#   all the remaining Decision Tree building is same as seen earlier

In [52]:
# #why we call it as ensemble??

# Instead of getting processed with one single decision tree

# It is getting processed with multiple decision trees

# and ur Random Forest internally comprises of multiple models,
# that's why we call it as Ensemble(collection of trees)

In [53]:
#Summary:
#i/p Records---->splitted into bag ofrecords
#for each bag,it generates a DecisionTree
#whenever you are prediting a record
#it gets o/p from each model
#and based on majority of votes,it predicts the majority class

#Normally in Datascience,we never say a particular model does well
#bcoz Datascience algorithms will fine tune based on ur datasets

#If your datasets are not good
#If your datasets are not quantitative
#If youe datasets are not qualitative
#ur algorithm wont do good

#so you need to explore with diff algorithms
#Some times Decision Tree does well
#sometimes RandomForest do well
#so explore and find the best one

**Random Forest Classifier Algoritm Implementation**

In [54]:
from sklearn.ensemble import RandomForestClassifier
#4 Things we perform

#1. Initialize the model
rf_model=RandomForestClassifier(n_estimators=10,criterion='gini',max_depth=None,min_samples_split=2,min_samples_leaf=1,random_state=5)

#2.applying fit--->Train the model with(X_train,y_train)
rf_model.fit(X_train,y_train)

#Now model got trained
#3.Model prediction on test data(X_test)--->we get y_pred
y_pred=rf_model.predict(X_test)

#4.Model evaluation

print("Classification Report for Logistic Regression Model:")
print("y_actual:",y_test.values)
print("y_pred  :",y_pred)

print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))

print("Precision Score(1):",precision_score(y_test,y_pred))
print("Precision Score(0):",precision_score(y_test,y_pred,pos_label=0))

print("Recall Score(1):",recall_score(y_test,y_pred))
print("Recall Score(0):",recall_score(y_test,y_pred,pos_label=0))

print("F1 Score(1):",f1_score(y_test,y_pred))
print("F1 Score(0):",f1_score(y_test,y_pred,pos_label=0))

print("ROC-AUC Score:",roc_auc_score(y_test,rf_model.predict_proba(X_test)[:,1]))

Classification Report for Logistic Regression Model:
y_actual: [0 0 1 0 0 1 0 1 0 0 0 1]
y_pred  : [0 0 1 0 0 1 1 0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.78      0.88      0.82         8
           1       0.67      0.50      0.57         4

    accuracy                           0.75        12
   macro avg       0.72      0.69      0.70        12
weighted avg       0.74      0.75      0.74        12

Accuracy Score: 0.75
Precision Score(1): 0.6666666666666666
Precision Score(0): 0.7777777777777778
Recall Score(1): 0.5
Recall Score(0): 0.875
F1 Score(1): 0.5714285714285714
F1 Score(0): 0.8235294117647058
ROC-AUC Score: 0.65625

In [55]:
#Random Forest also not doing well
#Exploring with hyper parameters(learning parameters)

#whenever we are initilializing this model, we provide many hyper paramters(learning parameters)
#such as
#1.  n_estimators=100 (100 default)
#2.  criterion='gini' / 'entropy'
#3.  max_depth=None  (depth of the tree)
#4.  min_samples_split=2
#5.  min_samples_leaf=1
#6.  random-state=value/None

In [56]:
#ex:
rf_model=RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=None,min_samples_split=2,min_samples_leaf=1,random_state=5)

#Default it takes 100 estimator----> i.e 100 decision Trees
#By default --->criterion ='gini'
#Change the criterion to---> entropy and check the result--> it got little improved
#min_samples_leaf=1, (means 1 record for leaf node always)

In [57]:
X_train.shape

(46, 7)

In [58]:
#There are only 46 records
#from this,we are going to run 100 estimators--->100Decision Trees

#100----->Too much of learning
#so instead of 100---->we take 10 and check the result
#so changining n_estimators=10 (changing hyper parameters)
#i got same result
#Change to 'gini' and estimators to 10 --->result got improved

#either gini or entropy--->here the main goal is--->how fast they traverse to leafnode quickly
#Here everytime--->it split, the records are getting changed
#but as i have given random state--->we same the same split of records
#So everytime you run--->your result will not change

#Now once change the no of estimators to 5 and check the result--->result is decreasing
#so chnage back the estimators to 10--->It is the best result among all

#hyper parameters also we need to exlore and select whcih gives good result

#Here Random Forest is not doing good

#here 46 records--->less quantity of data

#The model tends to underfit

**Naive Baye's Classifier**

In [59]:

# Every Algorithn is following its own different way of learning the dataset through
# which it is going to PredictionErrorDisplay

# Logistic Regression--->It is following odds ratio and using maximum likelyhood estimation
#                        it is going to build the best sigmoid curve

# Decision Tree----->?it is internally building tree-structure through which it learns

# Random Forest----->It is building multiple decision trees ans using ensemble mechanism
#                   it is going to learn


# Naive Bayes
#     - Based on Baye's Theorem

#     -It is a conditional probability

#what's Baye's Theorem

# It is a pure probability based approach

# It is given as--->P(A/B)=(P(B/A)*P(A))/P(B)

# Ex: Probability of email is spam/not-spam

# P(A/B)=(P(B/A)*P(A))/P(B)

# here P(A/B)---->Posterior Probability
#      P(B/A)---->likelyhood Probability (probability of features given class)
#      P(A)---->Prior Probability
#      P(B)---->Evidence Probability(probaility of i/p)


# P(A/B)--->here A --->probability of class A(ex: spam) with given features B
#                B---->based on certain condition (one condition/2conditions/multiple conditions)
#                                                  (1 feature/2features/multiple features)
# It calculates the probability for Every feature seperately
# Finally it gets the consolidated result

# Naive Baye's for doing this calculations ----->there is an assumption that
# all i/p variables are independent-->there should not be any dependency

# that's why it is called naive

# Why it's Naive

# Naive Bayes assumes---->Each feature contributes independenlty to the final outcome

# How Naive Bayes works:

# 1.Calculate the prior probaility P(A) for each class --->P(A/B)

# 2.Calculate the likelihood(P(B/A)) for each feature per class

# 3.multiply all probabilities using Baye's formula

# 4.Pick the class with maximum probaility




# Ex: Spam Detection

# Features : words in an email

# ouput class :  spam/Not spam


# email contains(features such as)----->"free" ,"offer"


# Naive Bayes Computes
# P(Spam/free,offer)

# P(NoSpam/free,offer)

# whichever is higher probability---predict that

# ex: classify email--->as spam or Not spam ---->based on 2 words
#     1)Free
#     2)Offer

#     #P(Spam/Free,Offer)=P(Free/Spam)*P(Offer/Spam)*P(Spam)
#     #P(notspam/Free,offer)=P(Free/notspam)*P(offer/notspam)*P(notspam)

#     Training Data

#     Email    Free  offer   class
#      1        yes    yes    spam
#      2        yes    No     spam
#      3        No     yes    Not spam
#      4        No     No     Not spam

#      Total emails=4

    #  Step 1: Calculate prior probabilities P(A)

    #     P(Spam)=2/4=0.5

    #     P(Not Spam)=2/4=0.5



    #   Step 2: Calculate the Likelihood probabilities (p(B/A))
    #             for each feature per class
    #           i.e P(Free/Spam)
              # i.e P(Offer/Spam)

              #  i.e P(Free/Not Spam)
              #  i.e P(Offer/Not Spam)
    #    i)For spam
    #    P(Free = Yes/spam) =2/2=1
    #    P(offer=Yes/spam) =1/2=0.5

    #    ii)For Not spam
    #    P(Free = Yes/Not spam) =0/2 =0
    #    P(offer=Yes/Not spam) =1/2=0.5


    #Step 3: classify a new Email
    #        Assume Free=yes and offer=yes

    #     Apply Baye's theorem -->compute posterior probability
    #      for spam
    #      P(Spam/Free,Offer)=P(Free/Spam)*P(Offer/Spam)*P(Spam)
    #                         =  1  *0.5 *0.5
    #                         =0.25
    #      for Not spam
    #      P(Not Spam/Free,Offer)=P(Free/Not Spam)*P(Offer/Not Spam)*P(NotSpam)
    #                        =  0  *0.5 *0.5
    #                        = 0

    #      Final prediction
    #        0.25 >0 ---->Email is classified as spam

 #==================================================================================
 #Bayes Theorem:

 #P(A/B)=(P(B/A)*P(A))/P(B)

 #P(Class/Features)=(P(Features/class)*P(class))/P(Features)

 #P(class/Features) i.e P(A/B)--->posterior probability (what we want)

 #P(B/A) i.e P(Features/Class)--->Likelyhood

 #P(class)--->Prior probability

 #P(Features)->Evidence(same for all classes)--->ignore while comparision

 #How Naive Bayes works or classifies

 #1.Compute the prior probabilties for each class  p(A)

 #2.Compute likelyhood of each feature in the class p(B/A)

 #3.multiply the above two

 #4.Pick the class with the highest probability

 #============================================================================
 #Ex:2
 #    Email Text               class
 #    "win money-2Lakhs"       Spam
 #    "Limited win project"    spam
 #    "DS project at 9pm"      not spam
 #    "No project class today" not spam

 #Step 1: compute Prior probabilities
 #        P(spam)=2/4=0.5    P(NotSpam)=2/4=0.as_integer_ratio

 #Classify--->"win","project"
 #Step 2: compute Likelihoods
 #        P("win"/spam)=2/2=1
 #        P("win"/notspam)=0/2=0

 #        P("project"/spam)=1/2=0.5
 #        P("project"/notspam)=2/2=1

 #Step 3:

   #Apply Baye's theorem
    #  comute posterior probability
    #      for spam
    #      P(Spam/win,project)=P(win/Spam)*P(project/Spam)*P(Spam)
    #                         =  1 *0.5*0.5
    #                         = 0.25
    #      for Not spam
    #      P(Not Spam/win,project)=P(win/Not Spam)*P(project/Not Spam)*P(NotSpam)
    #                        =  0  *1 *0.5
    #                        = 0

    #      Final prediction
    #        0.25 >0 ---->Email is classified as spam

  #===========================================================================
 #Ex:3

  #  Weather          Temperature        play tennis
  #  Sunny               Hot               No
  #  Sunny               mild              No
  #  overcast            cool              yes
  #  Rainy               Mild              yes

  #Task: will there will be a play when weather=Sunny Temperature=cool ???

   #Step 1: compute Prior probabilities
 #        P(yes)=2/4=0.5    P(No)=2/4=0.5

 #Classify--->"Sunny" ,"cool"
 #Step 2: compute Likelihoods
 #        P("sunny"/yes)=0/2 =0
 #        P("sunny"/no)=2/2=1

 #        P("cool"/yes)=1/2=0.5
 #        P("cool"/no)=0/2=0


#Step 3:

   #Apply Baye's theorem
    #  comute posterior probability
    #      for class "yes"
    #      P(yes/sunny,cool)=P(sunny/yes)*P(cool/yes)*P(yes)
    #                         =  0*0.5*0.5
    #                         = 0
    #      for class "No"
    #      P(No/sunny,cool)=P(sunny/No)*P(cool/No)*P(No)
    #                        =  1  *0 *0.5
    #                        = 0



    #      Final prediction--->internally it applies smoothing
    #
    #==========================================================================
  #ex:4 Medical Diagnosis (Binary Features)

  #Fever        Cough        Flu
  # yes          Yes         yes
  # yes          No          yes
  #No            Yes         No
  # No           No          No

  #predict for a new patient - Fever=yes cough=yes

  #Step 1: Prior probability
   #        P(A)--->probability of each class
   #        P(Flu)=2/4=0.5
   #        P(NoFlu)=2/4=0.5

  #step 2: likelihoods: P(B/A)
         #For the new patient
  #   P(Fever=Yes/Flu)=2/2=1
  #   P(cough=yes/Flu)=1/2=0.5

  #for noflu
  #  P(Fever=Yes/noFlu)=0/2=0
  #  P(Cough=yes/NoFlu)=1/2=0.5

  #Step 3:posterior probability
  #       P(flu/fever,cough)=P(fever/flu)*P(cough/flu)*P(flu)
  #                         =1*0.5*0.5
  #                         =0.25

  #       P(Noflu/fever,cough)=P(fever/noflu)*P(cough/noflu)*P(noflu)
  #                           =    0  * 0.5 *0.5
  #                           =0

  #Select the class with high probability--->P(flu) > P(Noflu)
  #                                           0.25  > 0

  #Conclusion :Flu predicted

#======================================================================================

#Types of Naive Baye's Classifiers:
#1)Gaussian Naive Baye's----->when features are continous
#                            It calculates the mean and standard deviation for each class
#                            to predict the outcomes
#                            suitable for data like-->height,weight,sensor measurements

#2.Multinominal "   " ------>For text classification where features represents wordcounts
#                            or frequencies---->mostly for frequency data
#                            ex: spam detection

#3.Bernoulli    "   " -----> For binary or boolean features(i.e 0/1,present/absent,yes/No)
#
#4.Categorical  "   "------>for categorical  data

#Multinomial and categorical are almost same

#which one is the best---->Gaussian/Bernoulli/multinominal/Categorical

#We cant say---->we need to explore---->as a hyper parameter(learning paramter)

#which variant is doing good,we need to explore

**Naive Bayes Algorithm**

In [95]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB,CategoricalNB

In [61]:
#1. Initialize the model
nb_model=GaussianNB()

#2.applying fit--->Train the model with(X_train,y_train)
nb_model.fit(X_train,y_train)

#Now model got trained
#3.Model prediction on test data(X_test)--->we get y_pred
y_pred=nb_model.predict(X_test)

#4.Model evaluation

print("Classification Report for Logistic Regression Model:")
print("y_actual:",y_test.values)
print("y_pred  :",y_pred)

print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))

print("Precision Score(1):",precision_score(y_test,y_pred))
print("Precision Score(0):",precision_score(y_test,y_pred,pos_label=0))

print("Recall Score(1):",recall_score(y_test,y_pred))
print("Recall Score(0):",recall_score(y_test,y_pred,pos_label=0))

print("F1 Score(1):",f1_score(y_test,y_pred))
print("F1 Score(0):",f1_score(y_test,y_pred,pos_label=0))

print("ROC-AUC Score:",roc_auc_score(y_test,nb_model.predict_proba(X_test)[:,1]))

Classification Report for Logistic Regression Model:
y_actual: [0 0 1 0 0 1 0 1 0 0 0 1]
y_pred  : [0 0 1 0 0 1 0 0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.50      0.67         4

    accuracy                           0.83        12
   macro avg       0.90      0.75      0.78        12
weighted avg       0.87      0.83      0.81        12

Accuracy Score: 0.8333333333333334
Precision Score(1): 1.0
Precision Score(0): 0.8
Recall Score(1): 0.5
Recall Score(0): 1.0
F1 Score(1): 0.6666666666666666
F1 Score(0): 0.8888888888888888
ROC-AUC Score: 0.5

In [62]:
#Result same as---->Logistic regression model

#So next try with BernouliNB()

In [63]:
#BernoulliNB
#1. Initialize the model
nb_model=BernoulliNB()

#2.applying fit--->Train the model with(X_train,y_train)
nb_model.fit(X_train,y_train)

#Now model got trained
#3.Model prediction on test data(X_test)--->we get y_pred
y_pred=nb_model.predict(X_test)

#4.Model evaluation

print("Classification Report for Logistic Regression Model:")
print("y_actual:",y_test.values)
print("y_pred  :",y_pred)

print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))

print("Precision Score(1):",precision_score(y_test,y_pred))
print("Precision Score(0):",precision_score(y_test,y_pred,pos_label=0))

print("Recall Score(1):",recall_score(y_test,y_pred))
print("Recall Score(0):",recall_score(y_test,y_pred,pos_label=0))

print("F1 Score(1):",f1_score(y_test,y_pred))
print("F1 Score(0):",f1_score(y_test,y_pred,pos_label=0))

print("ROC-AUC Score:",roc_auc_score(y_test,nb_model.predict_proba(X_test)[:,1]))

Classification Report for Logistic Regression Model:
y_actual: [0 0 1 0 0 1 0 1 0 0 0 1]
y_pred  : [0 0 1 0 0 1 0 0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.50      0.67         4

    accuracy                           0.83        12
   macro avg       0.90      0.75      0.78        12
weighted avg       0.87      0.83      0.81        12

Accuracy Score: 0.8333333333333334
Precision Score(1): 1.0
Precision Score(0): 0.8
Recall Score(1): 0.5
Recall Score(0): 1.0
F1 Score(1): 0.6666666666666666
F1 Score(0): 0.8888888888888888
ROC-AUC Score: 0.6875

In [64]:
#Each algorithm has different variants
#Each variant developed with diff type of dataset
#so we need to explore with diff variants and select the best for ur dataset

#ex: BernoulliNB()--->It has a hyper parameter--->alpha=1.0

#ex:alpha 1.0 is a Laplace somoothing parameter--->it avoids divide by zero errors

#ex: (P(B/A).P(A))/P(B) --->here we doesnt want P(B) becomong zero at anytime

#Generally to avoid zero-division error->we add 1->This is additive laplace smoothing parameter

#whichever hyper paramter you feel is doing good , you can consider that

#Generally people say-->RandomForest gives good results bcoz of ensemble
#but here it is not doing well as compared with logisitic regression

#so explore with other algorithms

**K-Nearest Neighbours(KNN) Classifer**

In [65]:
"""
KNN is  supervised machime LEarning algorithm used mainly for classification

It classifies a data point based on how its nearest neighbours are classified

Core methodology---->Distance metrics
                     based on closest distance, it learns/predicts

KNN says--->"Tell me who your neighbours are,I'will tell you who you are"

KNN is ----->"you are like your neighbours" algorithm

KNN is also called as a Lazy learner
bcoz, it doesnt perform anything during training phase but it starts
 computing at prediction time

 during predictiontime--->it applies the distance metrics

KNN Process:
  -when a new datapoint is given
  -It looks at the k closest and nearest datapoints in the training set
  -among those neighbours the class which has majority will be considered


HOw KNN works:

1.choose the value of k
  k=number of nearest neighbours to consider(ex,k=3 or k=5 or k=7)
  if k=5 ,then u are checking with 5 nearest neighbours

2.Calculate the distance
  measure the distance b/w the new datapoint and all other training points
  for calculating distance, we have 2 distance metrics
  i)Euclidean distance(mostly used)
 ii)Manhattan distance

3.Find k nearest neighbours
  select k-datapoints with  the smallest/nearest distance

4.Vote for the class
  The class with the maximum votes, that class is assigned to the new datapoint

  ex: k=5 and among 5 nearesst neighbours
      3 belong to classA
      2 belong to ClassB

      majority=3 belongs to class A

      So the new datapoint is classified as---> class A
"""

'\nKNN is  supervised machime LEarning algorithm used mainly for classification\n\nIt classifies a data point based on how its nearest neighbours are classified\n\nCore methodology---->Distance metrics\n                     based on closest distance, it learns/predicts\n\nKNN says--->"Tell me who your neighbours are,I\'will tell you who you are"\n\nKNN is ----->"you are like your neighbours" algorithm\n\nKNN is also called as a Lazy learner\nbcoz, it doesnt perform anything during training phase but it starts\n computing at prediction time\n\n during predictiontime--->it applies the distance metrics\n\nKNN Process:\n  -when a new datapoint is given\n  -It looks at the k closest and nearest datapoints in the training set\n  -among those neighbours the class which has majority will be considered\n\n\nHOw KNN works:\n\n1.choose the value of k\n  k=number of nearest neighbours to consider(ex,k=3 or k=5 or k=7)\n  if k=5 ,then u are checking with 5 nearest neighbours\n\n2.Calculate the distance\n  measure the distance b/w the new datapoint and all other training points\n  for calculating distance, we have 2 distance metrics\n  i)Euclidean distance(mostly used)\n ii)Manhattan distance\n\n3.Find k nearest neighbours\n  select k-datapoints with  the smallest/nearest distance\n\n4.Vote for the class\n  The class with the maximum votes, that class is assigned to the new datapoint\n\n  ex: k=5 and among 5 nearesst neighbours\n      3 belong to classA\n      2 belong to ClassB\n\n      majority=3 belongs to class A\n\n      So the new datapoint is classified as---> class A\n'

In [66]:
"""
we also call KNN as a Lazy learner
bcoz, it doesnt perform anything during training phase but it starts
 computing at prediction time

Applications:
  -pattern recognition
  -Image classifcation
  -Medical diagnosis
  -credit scoring
"""
"""
ex:1

   point        X         Y        class
    A           1         2          Red
    B           2         3          Red
    C           3         3          Blue
    D           6         5          Blue
    E           7         6          Blue

  New point to classifiy---> p=(2.5,2.5)

  #Step 1: It Compute distances

  Distance to A------>near
  Distance to B------>Very near
  Distance to C------>far
  Distance to D------>too far
  Distance to E------>too fat

  #step 2: Choose the value of k
       say k=3

   Nearest neighbours are:
      A(Red)
      B(Red)
      C(Blue)

  #step 3: MAjority vote
      Red-2
      Blue-1

  Prediction :Red


  commonly used Distance metrics is----->Euclidean Distance

  for two points p=(x1,x2)  q=(y1,y2)

  Distance =sqrt((x1-y1)square +(x2-y2)square)


EX: churn/Not-churn
             * * *
    |       * * *  ----->non-churn
    |        * * *
    | **   x ----->new given point (for this it checks the k-nearest points)
    |* * *------>churn
    | * **
    |___________________

    KNN ia a lazy learner--->During training phase it just plots
    And during prediction time it applies the distance metrics and gets the k-nearest
    neighbours and takes majority from that to predict the class

 ex:
     |
     |         * (4,3)
     |
     |          --------->Computing the distance b/w 2 points
     |  *(2,1)            Euclidean distance =sqrt((4-2)square+(3-1)square)
     |____________________

2)another distance metrics is----->Manhattan distance
   Distance =|x1-y1|+|x2-y2| (here istead of taking sqt ans square, it takes absolute value)

 so Distance=|2-4|+|1-3|

 default distance metrics used by KNN is-----> Euclidean distance

 where exactly  and when it uses distance metrics

 during predicting--->if any new record is kept to predict



 ex: k- here k means, how many neighbours,you want to validate
     ex: 5
     it checks for 5 neighbours
     in that 5 neighbours---> Non-churn =2
                              churn=3
                so finally predict the majority class---->say --->churn

-------------------------------------------------------------------------------
General equation for distance metrics
  Sum[(O1i-O2i)**p]**1/p

we call this as minkowski distance

here based on p value----->it decides--->whether it is Euclidean or Manhattan

p=1--->Manhattan distance
p=2--->Euclidean distance
in the above formula---->if you substiute p=2 then we get Euclidean distance formula
                    ----> "        "      p=1 then we get Manhattan distance formula
"""

'\nex:1\n\n   point        X         Y        class\n    A           1         2          Red\n    B           2         3          Red\n    C           3         3          Blue\n    D           6         5          Blue\n    E           7         6          Blue\n\n  New point to classifiy---> p=(2.5,2.5)\n\n  #Step 1: It Compute distances\n\n  Distance to A------>near\n  Distance to B------>Very near\n  Distance to C------>far\n  Distance to D------>too far\n  Distance to E------>too fat\n\n  #step 2: Choose the value of k\n       say k=3\n\n   Nearest neighbours are:\n      A(Red)\n      B(Red)\n      C(Blue)\n\n  #step 3: MAjority vote\n      Red-2\n      Blue-1\n\n  Prediction :Red\n\n\n  commonly used Distance metrics is----->Euclidean Distance\n\n  for two points p=(x1,x2)  q=(y1,y2)\n\n  Distance =sqrt((x1-y1)square +(x2-y2)square)\n\n\nEX: churn/Not-churn\n             * * *\n    |       * * *  ----->non-churn\n    |        * * *\n    | **   x ----->new given point (for this it checks the k-nearest points)\n    |* * *------>churn\n    | * **\n    |___________________\n\n    KNN ia a lazy learner--->During training phase it just plots\n    And during prediction time it applies the distance metrics and gets the k-nearest\n    neighbours and takes majority from that to predict the class\n\n ex:\n     |\n     |         * (4,3)\n     |\n     |          --------->Computing the distance b/w 2 points\n     |  *(2,1)            Euclidean distance =sqrt((4-2)square+(3-1)square)\n     |____________________\n\n2)another distance metrics is----->Manhattan distance\n   Distance =|x1-y1|+|x2-y2| (here istead of taking sqt ans square, it takes absolute value)\n\n so Distance=|2-4|+|1-3|\n\n default distance metrics used by KNN is-----> Euclidean distance\n\n where exactly  and when it uses distance metrics\n\n during predicting--->if any new record is kept to predict\n\n\n\n ex: k- here k means, how many neighbours,you want to validate\n     ex: 5\n     it checks for 5 neighbours\n     in that 5 neighbours---> Non-churn =2\n                              churn=3\n                so finally predict the majority class---->say --->churn\n\n-------------------------------------------------------------------------------\nGeneral equation for distance metrics\n  Sum[(O1i-O2i)**p]**1/p\n\nwe call this as minkowski distance\n\nhere based on p value----->it decides--->whether it is Euclidean or Manhattan\n\np=1--->Manhattan distance\np=2--->Euclidean distance\nin the above formula---->if you substiute p=2 then we get Euclidean distance formula\n                    ----> "        "      p=1 then we get Manhattan distance formula\n'

**K-Nearest Neighbors Implementation**

In [67]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
#1. Initialize the model
knn_model=KNeighborsClassifier(n_neighbors=3)

#2.applying fit--->Train the model with(X_train,y_train)
knn_model.fit(X_train,y_train)

#Now model got trained
#3.Model prediction on test data(X_test)--->we get y_pred
y_pred=knn_model.predict(X_test)

#4.Model evaluation

print("Classification Report for KNN Model:")
print("y_actual:",y_test.values)
print("y_pred  :",y_pred)

print(classification_report(y_test,y_pred))

print("Accuracy Score:",accuracy_score(y_test,y_pred))

print("Precision Score(1):",precision_score(y_test,y_pred))
print("Precision Score(0):",precision_score(y_test,y_pred,pos_label=0))

print("Recall Score(1):",recall_score(y_test,y_pred))
print("Recall Score(0):",recall_score(y_test,y_pred,pos_label=0))

print("F1 Score(1):",f1_score(y_test,y_pred))
print("F1 Score(0):",f1_score(y_test,y_pred,pos_label=0))

print("ROC-AUC Score:",roc_auc_score(y_test,knn_model.predict_proba(X_test)[:,1]))

Classification Report for KNN Model:
y_actual: [0 0 1 0 0 1 0 1 0 0 0 1]
y_pred  : [0 0 0 0 0 0 0 1 0 1 1 1]
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.50      0.50      0.50         4

    accuracy                           0.67        12
   macro avg       0.62      0.62      0.62        12
weighted avg       0.67      0.67      0.67        12

Accuracy Score: 0.6666666666666666
Precision Score(1): 0.5
Precision Score(0): 0.75
Recall Score(1): 0.5
Recall Score(0): 0.75
F1 Score(1): 0.5
F1 Score(0): 0.75
ROC-AUC Score: 0.75

In [69]:
# showing 0 for f1score
#Explore with hyper paramters(learning parameters)
#now change the n_neighbours=3
#we see increase in resuts AUC score ---->0.75
#now change the n_neighbours=2 --->show 0 for f1score
#now change the n_neighbours=4 --->show 0 for f1scoe

#so keep the n_neighbours=3


#Next--->here by deafault p=2 ---->It has taken Euclidean distance
#       if i change p=1 --->manhattan distance and check--->0 for f1score
#        so keep p=2 only

**Support Vector MAchine(SVM) classifier**

In [70]:
"""
SVM is a supervised learning algorithm mainly used for classification(also regression)

objective : Finding the best boundary(decision boundary) that seperates different classes
with the maximum margin

Decision Boundary----->Hyperplane

The hyperplane seperates the classes

What is MArgin??

Margin =distance b/w the decision boundary and the nearest data points from each class

Better margin =better generalization

SVM tries to maximize this margin

What do you mean by support vectors???

Support vectors are the data points that are closest to the decision boundary

or->the closest datapoints to the decision boundary-->these points only define the boundary

If you remove other points which are not close, the boundary doesnt change---->but if
you remove closest datapoints(support vectors) then the boundary changes


SVM --->It is going to classify your data as linear line
        It is not only for linear classifcation but also for non-linear classification

        ur datapoints will be plotted in multi-dimensional space as shown in diagram

        Main Responsibility of SVM is---->forming a hyper plane with the margins
         which divides the 2 classes

        within the 2 margin  distance(i,e with the boundaries) there should be any datapoints

        Here we see---->linear hyperplane
                        polynomial hyperplane for dividing the classes

        here we will be exploring with the hyper parameters-->'linear' or 'polynomial'

       SVM--->Seperating the datapoints using margins

       in SVM classifier implementation--->
             by default  the probanility set to False -->make it true
             by saying----> probability=True

RBF--->Radial Basis Function
      This RBF is used to handle non-Linear,complex datasets by mapping i/p data
      allowing linear and non-linear seperation of data

      Hyper parameters---->Linear,polynomial,RBF
      In RBF,the decision boundaries--->instead of straight line, it forms
      complex closed-loop boundaries

      when to go for RBF:
     1) when data is not seperable using linear straight line or polynomial curved hyperplane
      we go with these closed-loop boundaries
     2)when dealing with high-dimensional data and where relationships are complex

     3)RBF is the first choice for non-Linear classificarion

     The performance is highly dependant  on tuning the parameters and the margin width

     RBF is popular choice for non-linear classification
     i.e for non-linear decision boundaries

     maily 3 hyper parmaters--->linear,polynomial and RBF

     in real use cases--->hyper parameters tuning is very important

     To bring the accuracy from 83% to 85%---->we spent lot of time
"""

"\nSVM is a supervised learning algorithm mainly used for classification(also regression)\n\nobjective : Finding the best boundary(decision boundary) that seperates different classes\nwith the maximum margin\n\nDecision Boundary----->Hyperplane\n\nThe hyperplane seperates the classes\n\nWhat is MArgin??\n\nMargin =distance b/w the decision boundary and the nearest data points from each class\n\nBetter margin =better generalization\n\nSVM tries to maximize this margin\n\nWhat do you mean by support vectors???\n\nSupport vectors are the data points that are closest to the decision boundary\n\nor->the closest datapoints to the decision boundary-->these points only define the boundary\n\nIf you remove other points which are not close, the boundary doesnt change---->but if\nyou remove closest datapoints(support vectors) then the boundary changes\n\n\nSVM --->It is going to classify your data as linear line\n        It is not only for linear classifcation but also for non-linear classification\n\n        ur datapoints will be plotted in multi-dimensional space as shown in diagram\n\n        Main Responsibility of SVM is---->forming a hyper plane with the margins\n         which divides the 2 classes\n\n        within the 2 margin  distance(i,e with the boundaries) there should be any datapoints\n\n        Here we see---->linear hyperplane\n                        polynomial hyperplane for dividing the classes\n\n        here we will be exploring with the hyper parameters-->'linear' or 'polynomial'\n\n       SVM--->Seperating the datapoints using margins\n\n       in SVM classifier implementation--->\n             by default  the probanility set to False -->make it true\n             by saying----> probability=True\n\nRBF--->Radial Basis Function\n      This RBF is used to handle non-Linear,complex datasets by mapping i/p data\n      allowing linear and non-linear seperation of data\n\n      Hyper parameters---->Linear,polynomial,RBF\n      In RBF,the decision boundaries--->instead of straight line, it forms\n      complex closed-loop boundaries\n\n      when to go for RBF:\n     1) when data is not seperable using linear straight line or polynomial curved hyperplane\n      we go with these closed-loop boundaries\n     2)when dealing with high-dimensional data and where relationships are complex\n\n     3)RBF is the first choice for non-Linear classificarion\n\n     The performance is highly dependant  on tuning the parameters and the margin width\n\n     RBF is popular choice for non-linear classification\n     i.e for non-linear decision boundaries\n\n     maily 3 hyper parmaters--->linear,polynomial and RBF\n\n     in real use cases--->hyper parameters tuning is very important\n\n     To bring the accuracy from 83% to 85%---->we spent lot of time\n"

**Support Vector Implementation**

In [71]:
from sklearn.svm import SVC

In [72]:
#initilize the model
svc_model=SVC(kernel='linear',probability=True,random_state=7)

#2.applying fit--->Train the model with(X_train,y_train)
svc_model.fit(X_train,y_train)

#Now model got trained
#3.Model prediction on test data(X_test)--->we get y_pred
y_pred=svc_model.predict(X_test)

#4.Model evaluation

print("Classification Report for SVC Model:")
print("y_actual:",y_test.values)
print("y_pred  :",y_pred)

print("Confusion matrix for SVC model")
print(classification_report(y_test,y_pred))
print("Accuracy Score:",accuracy_score(y_test,y_pred))

print("Precision Score(1):",precision_score(y_test,y_pred))
print("Precision Score(0):",precision_score(y_test,y_pred,pos_label=0))

print("Recall Score(1):",recall_score(y_test,y_pred))
print("Recall Score(0):",recall_score(y_test,y_pred,pos_label=0))

print("F1 Score(1):",f1_score(y_test,y_pred))
print("F1 Score(0):",f1_score(y_test,y_pred,pos_label=0))

print("ROC-AUC Score:",roc_auc_score(y_test,knn_model.predict_proba(X_test)[:,1]))

Classification Report for SVC Model:
y_actual: [0 0 1 0 0 1 0 1 0 0 0 1]
y_pred  : [0 0 1 0 0 1 0 0 0 0 0 0]
Confusion matrix for SVC model
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.50      0.67         4

    accuracy                           0.83        12
   macro avg       0.90      0.75      0.78        12
weighted avg       0.87      0.83      0.81        12

Accuracy Score: 0.8333333333333334
Precision Score(1): 1.0
Precision Score(0): 0.8
Recall Score(1): 0.5
Recall Score(0): 1.0
F1 Score(1): 0.6666666666666666
F1 Score(0): 0.8888888888888888
ROC-AUC Score: 0.75

In [73]:
#Next try with kernel='linear'
#svc_model=SVC(kernel='linear',probability=True,random_state=7)
#Got good results as compared with 'rbf', almost equal to Logistic regression
#here results got improved--->means ur dataset has got lot of linearity

#Also check with--->kernel='poly'
#results are bad as compared with 'Linear' --->change it to linear

In [74]:
"""
here in SVC---->I was manually modifying the hyperparmaters
i.e linear/polynomial/rbf

Is there any library that supports this hyper paramter tuning where i will pass
list of diff values as hyper paramters and internally it should run and should give
you the good results

i.e i want the best Estimato  where we can pass list of values--->which are of
multiple combination of hyperparamter values

-for every combination,it runs the model, vapture the result and
 finally it gives the best estimator in which the accuracy /result is very high

so for that automatic tuning of hyper parameters , we have 2 libraries

1)Grid search hyperparamter
2)Random searc hyperparmater

1)Grid search hyperparamter --->
                I want to explore kernel as-->kernel=[Linear,poly,RBF]

This Grid search first runs ur model withLinear and checks the accuracy
                secondy runs ur model with poly and checks the accuracy
                thirdly runs ur model with RBF and checks the accuracy

which one gives best---->That is the estimator

Grid---->takes all the combinations and gives the best estimator

but for larger daasets---->Too many combinations

then grid search takes longer time

So to perform quick testing--->Then go for Random Search

It wont search for all the combinations

It randomly picks any value--->ex:Linear and checks the accuracy and compares with other
like poly
but it wont check with all combinations

Advantage--->Random search is faster

Drawback of Random search: some Good Accuracy is missed

For production-ready model--->Go for grid search

So Grid search---->identifies the best combination of results
"""

'\nhere in SVC---->I was manually modifying the hyperparmaters\ni.e linear/polynomial/rbf\n\nIs there any library that supports this hyper paramter tuning where i will pass\nlist of diff values as hyper paramters and internally it should run and should give\nyou the good results\n\ni.e i want the best Estimato  where we can pass list of values--->which are of\nmultiple combination of hyperparamter values\n\n-for every combination,it runs the model, vapture the result and\n finally it gives the best estimator in which the accuracy /result is very high\n\nso for that automatic tuning of hyper parameters , we have 2 libraries\n\n1)Grid search hyperparamter\n2)Random searc hyperparmater\n\n1)Grid search hyperparamter --->\n                I want to explore kernel as-->kernel=[Linear,poly,RBF]\n\nThis Grid search first runs ur model withLinear and checks the accuracy\n                secondy runs ur model with poly and checks the accuracy\n                thirdly runs ur model with RBF and checks the accuracy\n\nwhich one gives best---->That is the estimator\n\nGrid---->takes all the combinations and gives the best estimator\n\nbut for larger daasets---->Too many combinations\n\nthen grid search takes longer time\n\nSo to perform quick testing--->Then go for Random Search\n\nIt wont search for all the combinations\n\nIt randomly picks any value--->ex:Linear and checks the accuracy and compares with other\nlike poly\nbut it wont check with all combinations\n\nAdvantage--->Random search is faster\n\nDrawback of Random search: some Good Accuracy is missed\n\nFor production-ready model--->Go for grid search\n\nSo Grid search---->identifies the best combination of results\n'

**Hyper Parameter Tuning**

In [75]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

#our Logistic Regression is giving good result

#What are the varous combinations--->check the logistic regression hyper paramters

#whatever hyperparamters i want to explore ,I want to keep in one dictionary

#From Logistic regression, am picking randomly 3 hyper paramters, we can go for more also
#am placing these 3 hyper paramters in a dictionary

In [76]:
#working with Randomizedsearch

In [77]:
param_log_reg={
      'C':np.logspace(-3,3,7),
      'penalty':['l1','l2'],
      'solver': ['liblinear','saga']
}

In [78]:
np.logspace(-3,3,7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

In [79]:
#These are the diff hyper paramters i want to explore
#for example it takes combinations such as---> 3 from 'C', 'l1' from penalty ,'saga' from solver
# as one combination
#In this way it checks with the all combinations -->-3,'l2','liblinear' (or) many other combinations

In [80]:
logistic_reg_model=LogisticRegression()
#Initializing the RandomizedSearch
random_search=RandomizedSearchCV(logistic_reg_model,param_distributions=param_log_reg,n_iter=10,cv=5)

In [81]:
"""
here n_iter=10  for every combination

cv=5
cv----->means cross validation
we say k-5 cross validation

It takes ur training data and is using k-5 i.e 5-fold cross validation

ex: assume 10 records as part of training

  cv=5
  means it divides the 10 recs into 5splits

  such as ---->   | 1 | 2 | 3 | 4 | 5|

  1st time--->it takes--->1 as test and all the remaining splits(2,3,4,5) as train
  2ndtime--->it takes---->2 as test and all the remaining splits(1,3,4,5) as train
  3rdtime--->it takes---->3 as test and all the remaining splits(1,2,4,5) as train

  so ur train data divided into multiple splits and within that it takes
  multiple combinations of test and train data
  and for each combination it captures the result
  on which combination,it is giving good result it will be picked as best estimator

  here in k-5 cross validation--->1split as test and 4splits as train

  It tries every combination and gives the best estimator
"""

'\nhere n_iter=10  for every combination\n\ncv=5\ncv----->means cross validation\nwe say k-5 cross validation\n\nIt takes ur training data and is using k-5 i.e 5-fold cross validation\n\nex: assume 10 records as part of training\n\n  cv=5\n  means it divides the 10 recs into 5splits\n\n  such as ---->   | 1 | 2 | 3 | 4 | 5|\n\n  1st time--->it takes--->1 as test and all the remaining splits(2,3,4,5) as train\n  2ndtime--->it takes---->2 as test and all the remaining splits(1,3,4,5) as train\n  3rdtime--->it takes---->3 as test and all the remaining splits(1,2,4,5) as train\n\n  so ur train data divided into multiple splits and within that it takes\n  multiple combinations of test and train data\n  and for each combination it captures the result\n  on which combination,it is giving good result it will be picked as best estimator\n\n  here in k-5 cross validation--->1split as test and 4splits as train\n\n  It tries every combination and gives the best estimator\n'

In [82]:
#here scoring ="accuracy"
#I can be also provide scoring as F1-score, precision, precision score,recall, for which i want to improve
#If i want to improve F1-score, provide this as scoring

#We have intialized randomized search

#next training using fit()

In [83]:
random_search.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['liblinear', 'saga']})

In [84]:
#Now you want to see the best parameter among all the combinations
random_search.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': np.float64(0.001)}

In [85]:
#It is providing the above as best params
#on this best params--->what is the results(accuracy) i got---> i want to check

random_search.best_score_

np.float64(0.6533333333333332)

In [86]:
#65% accuracy
#out of all diff explanations--->I was able to ge 65% of accuracy

In [87]:
#Let us try with grid search as randomized search should have missed some combinations
# or accuracy
#For GridSearch---> no need of n_iter (no of iterations) ,remove that argument

In [88]:
#Initializing the RandomizedSearch
grid_search=GridSearchCV(logistic_reg_model,param_grid=param_log_reg,cv=5,scoring='accuracy')

In [89]:
#Train using X_train and y_train
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2'],
                         'solver': ['liblinear', 'saga']},
             scoring='accuracy')

In [90]:
#it provides the best params
grid_search.best_params_

{'C': np.float64(0.001), 'penalty': 'l1', 'solver': 'liblinear'}

In [91]:
#check the results(Accuracy) on this best params
grid_search.best_score_

np.float64(0.6533333333333332)

In [92]:
#accuracy--->same --->No change in accuracy
#For smaller dataset--->we wont find any difference

#So here manuallly you no need to explore
#keep all the hyper paramters as a dictionary